- name: Firefox
  command: firefox

- name: Spotify
  command:
    "bash -c
    'pgrep spotify ||
    ((swaymsg workspace number 10 && spotify)
    & (sleep 1 && rmdir $HOME/Downloads/))'"

- name: Neovim
  command:
    "alacritty -e bash -c
    'FZF_DEFAULT_OPTS=--color=fg:#dddddd,bg:#181a26,hl:#bd93f9,fg+:#ffffff,\
    bg+:#181a26,hl+:#bd93f9,info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6,\
    marker:#ff79c6,spinner:#ffb86c,header:#6272a4
    nvim'"

- name: Zathura
  command:
    "alacritty -e bash -c
    'FZF_DEFAULT_OPTS=--color=fg:#dddddd,bg:#181a26,hl:#bd93f9,fg+:#ffffff,\
    bg+:#181a26,hl+:#bd93f9,info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6,\
    marker:#ff79c6,spinner:#ffb86c,header:#6272a4
    zathura-fuzzy'"

- name: Gimp
  command: gimp

- name: Feh
  command:
    "alacritty -e bash -c
    'FZF_DEFAULT_OPTS=--color=fg:#dddddd,bg:#181a26,hl:#bd93f9,fg+:#ffffff,\
    bg+:#181a26,hl+:#bd93f9,info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6,\
    marker:#ff79c6,spinner:#ffb86c,header:#6272a4
    feh-fuzzy'"
