#!/usr/bin/env bash

SESSIONDIR="$HOME/.config/bitwarden"
SESSIONFILE="$SESSIONDIR/session"
mkdir -p $SESSIONDIR
touch $SESSIONFILE
FLAG=true

while $FLAG; do
    PASSWORD=$(bw get password $1 --session $(cat $SESSIONFILE) 2> /dev/null)
    if [ $? -eq 0 ]; then
        echo $PASSWORD
        FLAG=false
    else
        bw unlock --raw > $SESSIONFILE
    fi
done
