#!/usr/bin/env bash

HASH=$(shasum <<< $1 | cut -f 1 -d ' ')
PWFILE="$HOME/tmp/$HASH"
mkdir -p $(dirname $PWFILE)

# if password exists then read it
if [[ -e $PWFILE ]]; then
    cat $PWFILE
else
    PW=$(bw get password $1)
    if [ $? == 0 ]; then
        echo $PW > $PWFILE
        cat $PWFILE
    fi
fi
