#!/usr/bin/env bash

mbsync -qqa
COUNT=$(find ~/mail/princeton/INBOX/new/ ~/mail/gmail/INBOX/new/ -type f | wc -l)

if [ "$COUNT" -ge "1" ]; then
    echo '{"text": "Mail '$COUNT'", "class": "new_mail"}'
else
    echo '{"text": "Mail", "class": "no_mail"}'
fi
