#!/usr/bin/env bash

STATUS=$(systemctl is-active --user mbsync)
COUNT=$(find ~/mail/princeton/INBOX/new/ ~/mail/gmail/INBOX/new/ -type f | wc -l)

if [ "$STATUS" = "active" ]; then

    if [ "$COUNT" -ge "1" ]; then
        echo '{"text": "Mail $COUNT", "class": "new_mail"}'
    else
        echo '{"text": "Mail", "class": "no_mail"}'
    fi

else
    echo '{"text": "Mail", "class": "inactive"}'
fi
