#!/bin/bash

workspaces() {
    A=$(hyprctl monitors -j | jq '.[].activeWorkspace.id')
    W=$(hyprctl workspaces -j |
        jq -c --arg A "$A" 'map(.id) | sort |
        map(. | {id: (. % 10), current: (. | tostring == $A)})')
    echo $W
}

workspaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	workspaces
done
