format = """
$hostname\
$sudo\
$directory\
$vcsh\
$git_branch\
$git_commit\
${custom.git_tag}\
$git_state\
$git_status\
$git_metrics\
$package\
$nix_shell\
$env_var\
$jobs\
$cmd_duration\
$status\
$character"""

add_newline = false
palette = "catppuccin_mocha"

[sudo]
format = "‍[[as](bold subtext1) sudo ](bold red)"
disabled = true

[directory]
truncation_length = 1
truncate_to_repo = false
fish_style_pwd_dir_length = 4
format = "[[$path](bold sky) ](bold subtext1)"

[git_branch]
format = "[on [$branch](bold bright-yellow) ](bold subtext1)"
ignore_branches = ["HEAD"]

[git_commit]
only_detached = true
tag_disabled = true
format = "[on [$hash $tag](bold yellow)](bold subtext1)"

[custom.git_tag]
command = "echo \\($(git tag --points-at HEAD)\\)"
when = "git describe --exact-match --tags $(git log -n1 --pretty='%h')"
format = "[$output ](bold yellow)"

[git_state]
format = "\\([$state( $progress_current/$progress_total)](bold yellow)\\) "

[git_status]
style = "bold yellow"
format = "([\\($all_status$ahead_behind\\)]($style) )"
ahead = "[↑](bold text)"
behind = "[↓](bold text)"
diverged = "[↑↓](bold text)"
conflicted = "[=](bold red)"
up_to_date = ""
untracked = "[?](bold mauve)"
stashed = "[S](bold text)"
staged = "[+](bold green)"
modified = "[!](bold red)"
renamed = "[r](bold red)"
deleted = "[d](bold red)"

[git_metrics]
disabled = true

[package]
disabled = true

[jobs]
number_threshold = 1
format = "[[bg](bold subtext1) $number](bold mauve) "
disabled = true

[cmd_duration]
format = "[took [$duration](bold mauve) ](bold subtext1)"
min_time = 1
show_milliseconds = true

[time]
disabled = true

[nix_shell]
format = '[nix](bold blue) '

[status]
disabled = false
format = "[$status( $common_meaning)( $signal_name)](bold red) "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
