[
  ./alacritty/alacritty.nix
  ./bash/bash.nix
  ./bat/bat.nix
  ./davmail.nix
  ./feh.nix
  ./git/git.nix
  ./latex/latex.nix
  ./mbsync.nix
  ./mime.nix
  ./neomutt/neomutt.nix
  ./neovim/neovim.nix
  ./rclone/rclone.nix
  ./ripgrep.nix
  ./rofi/rofi.nix
  ./python/python.nix
  ./spotify.nix
  ./starship/starship.nix
  ./sway.nix
  ./swaylock.nix
  ./systemd.nix
  ./vivid/vivid.nix
  ./waybar.nix
  ./zathura.nix
]
