{...}:
[
    #../config/alacritty.nix
    #../config/bash/bash.nix
    #../config/feh.nix
    #../config/git/git.nix
    #../config/julia/julia.nix
    #../config/latex/latex.nix
    #../config/mbsync.nix
    #../config/mime.nix
    #../config/neomutt/neomutt.nix
    #../config/neovim/neovim.nix
    #../config/rclone/rclone.nix
    #../config/ripgrep.nix
    #../config/rofi/rofi.nix
    #../config/starship/starship.nix
    #../config/sway.nix
    #../config/swaylock.nix
    #../config/systemd.nix
    #../config/vivid/vivid.nix
    #../config/waybar.nix
    #../config/zathura.nix
]
