colors:
  # based off of solarized vivid theme and dracula/dircolors
  # Based on 'dracula' theme
  # (https://draculatheme.com/)
  #
  # The assignment of colors to file types roughly follows `dircolors`

  black   :  '282a36'
  green   :  '50fa7b'
  purple  :  'bd93f9'
  red     :  'ff5555'
  yellow  :  'f1fa8c'
  cyan    :  '8be9fd'
  pink    :  'ff92df'
  orange  :  'ffb86c'
  white   :  'f8f8f2'
  base01  :  '3a3c4e'
  comment :  '6272a4'

core:
  normal_text:
    foreground: white

  regular_file:
    foreground: white

  reset_to_normal:
    foreground: orange

  directory:
    foreground: purple
    font-style: bold

  symlink:
    foreground: cyan

  multi_hard_link: {}

  fifo:
    foreground: yellow
    background: black

  socket:
    foreground: pink
    background: black
    font-style: bold

  door:
    foreground: pink
    background: black
    font-style: bold

  block_device:
    foreground: yellow
    background: black
    font-style: bold

  character_device:
    foreground: yellow
    background: black
    font-style: bold

  broken_symlink:
    foreground: red
    font-style: bold

  missing_symlink_target:
    foreground: red
    font-style: bold

  setuid:
    foreground: white
    background: red

  setgid:
    foreground: black
    background: yellow

  file_with_capability: {}

  sticky_other_writable:
    foreground: black
    background: green

  other_writable:
    foreground: purple
    background: green

  sticky:
    foreground: white
    background: purple

  executable_file:
    foreground: green

text:
  special:
    foreground: yellow
    font-style: bold

  todo:
    foreground: yellow
    font-style: bold

  licenses:
    foreground: yellow
    font-style: bold

  configuration:
    foreground: orange

  other:
    foreground: white

markup:
  foreground: purple

programming:
  foreground: yellow

  tooling:
    foreground: orange

    build:
      foreground: yellow
      font-style: bold


media:
  image:
    foreground: pink

  audio:
    foreground: pink

  video:
    foreground: pink

  fonts:
    foreground: orange

office:
  foreground: orange

archives:
  foreground: red
  font-style: bold

executable:
  foreground: green

unimportant:
  foreground: comment
