#!/usr/bin/python

import json, subprocess

# get i3 process tree
tree = subprocess.check_output(['i3-msg', '-t', 'get_tree'])
tree = json.loads(tree)

# get i3 workspace list
workspaces = subprocess.check_output(['i3-msg', '-t', 'get_workspaces'])
workspaces = json.loads(workspaces)

# build list of busy workspaces
busy_nums = 100 * [0]
for node in tree['nodes'][1]['nodes'][1]['nodes']:
  num = node['num']
  print(num)
  if(node['nodes']):
    busy_nums[num] = 1

# get first empty workspace
first_empty = min([i for i in range(1, len(busy_nums)) if busy_nums[i] == 0])
print(first_empty)

# move window to first empty workspace
subprocess.call(['i3-msg', 'move workspace number %i' % first_empty])
