#!/usr/bin/env bash

# check using laptop
if [ $HOSTNAME == "xanth" ]; then

    # cycle monitors
    if [ $(mons | grep -c "primary\|duplicate\|extend") -ne 0 ]; then
        echo "Current monitor: primary/duplicate/extend/..."
        mons -s
        echo "New monitor: secondary..."

    elif [ $(mons | grep -c second) -ne 0 ]; then
        echo "Current monitor: secondary..."
        mons -o
        echo "New monitor: primary..."
    fi

fi
