#!/usr/bin/env sh

if [ "$1" = "" ]; then
    echo ~ && exit
elif zoxide query "$1" > /dev/null 2>&1; then
    zoxide query "$1"
elif cd "$1" > /dev/null 2>&1; then
    echo "$1"
else
    >&2 echo "zoxide: No such file or directory"
    exit 1
fi
