#!/bin/bash
#
# optpdf file.pdf
# attempt to optimize a pdf for size

file="$1"
filebase="$(basename "$file" .pdf)"
optfile="/tmp/$$-${filebase}_opt.pdf"
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dNOPAUSE -dQUIET -dBATCH \
        -sOutputFile="${optfile}" "${file}"

if [ $? == '0' ]; then
    optsize=$(stat -c "%s" "${optfile}")
    orgsize=$(stat -c "%s" "${file}")
    percent=$(expr $optsize '*' 100 / $orgsize)
    optsizehuman=$(du -h "${optfile}" | cut -f1)
    orgsizehuman=$(du -h "${file}" | cut -f1)
    if [ "${optsize}" -eq 0 ]; then
        echo "optpdf $file: no output. keeping original"
        rm -f "${optfile}"
        exit;
    fi
    if [ ${optsize} -ge ${orgsize} ]; then
        echo "optpdf $file: didn't make smaller. keeping original"
        rm -f "${optfile}"
        exit;
    fi
    echo "optpdf $file: now $optsizehuman, ${percent}% of old"
    rm "${file}"
    mv "${optfile}" "${file}"
fi
