#!/usr/bin/env bash

new_email="%{F#ffaaff}Mail"
no_email="Mail"
inactive="%{F#ff612e}Mail"

while true; do

    # check syncing status
    status_Princeton=$(systemctl is-active --user offlineimap@Princeton)
    status_Gmail=$(systemctl is-active --user offlineimap@Gmail)
    status="$status_Princeton$status_Gmail"

    # count emails
    count_email=$(find ~/Mail/Princeton/INBOX/new/ ~/Mail/Gmail/INBOX/new/ -type f | wc -l)

    # display output
    if [ "$status" = "activeactive" ]; then

        if [ "$count_email" -ge "1" ]; then
            echo "$new_email $count_email"
        else
            echo "$no_email"
        fi

    else
        echo "$inactive"
    fi

    sleep 5
done
