#!/usr/bin/env bash

while true; do

  current_status=$(cat ~/sct_status)

  if [ "$current_status" == "on" ]; then
      echo "%{F#ffb86c}Sct"
  else
      echo "%{F#bbeeff}Sct"
  fi

  sleep 2

done
