#!/usr/bin/env bash

BAR_ICON=""
#NOTIFY_ICON=/usr/share/icons/Papirus/32x32/apps/system-software-update.svg

get_total_updates() { UPDATES=$(checkupdates 2>/dev/null | wc -l); }

while true; do
    get_total_updates

    # when there are updates available
    while (( UPDATES > 0 )); do
        if (( UPDATES > 99 )); then
            echo "%{F#f4511e} $UPDATES"
        else
            echo "%{F#f1fa8c} $UPDATES"
        fi
        sleep 300
        get_total_updates
    done

    # when no updates are available
    while (( UPDATES == 0 )); do
        echo ""
        sleep 300
        get_total_updates
    done
done
