#!/usr/bin/env bash

disconnected="%{F#ff612e}Net"
wireless_connected="Net"
ethernet_connected="Net"

ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 2
        else
            echo "$wireless_connected" ; sleep 2
        fi
    else
        echo "$disconnected" ; sleep 2
    fi
done
