#!/usr/bin/env bash

get_total_updates() { UPDATES=$(checkupdates 2>/dev/null | wc -l); }

while true; do
    get_total_updates

    # when there are updates available
    while (( UPDATES > 0 )); do
        if (( UPDATES > 99 )); then
            echo "%{F#f4511e}PKG $UPDATES"
        else
            echo "%{F#f1fa8c}PKG $UPDATES"
        fi
        sleep 300
        get_total_updates
    done

    # when no updates are available
    while (( UPDATES == 0 )); do
        echo "PKG"
        sleep 300
        get_total_updates
    done
done
