#!/usr/bin/env bash

# sync location
loc="/home/will/Documents/remarkable/"
echo "Remarkable files syncing to $loc"

# list the remarkable files to sync
files=(
    #"KDE research scratch"
    #"Teaching scratch"
    #"Regression research scratch"
    #"Martingales research scratch"
    #"Forests research scratch"
    "Seminar notes"
    #"Useful results"
)

# see all available files
echo "Updating file list..."
rmapi ls > "$loc/remarkable_list.txt" 2>/dev/null
cat "$loc/remarkable_list.txt"

# download and convert selected files to pdf
echo "Syncing and converting files to PDF..."
for f in "${files[@]}"; do
    (
        echo "    $f"
        cd $loc
        rmapi get "$f" > /dev/null 2>&1
        python -m rmrl "$loc/$f.zip" > "$loc/$f.pdf"
        #rm "$loc/$f.zip"
    )
done

echo "Finished sync"
