#!/usr/bin/env bash

# Screen temperatures
temp_night=2500
temp_day=6500

current_status=$(cat ~/sct_status)

if [ "$current_status" == "on" ]
then
    sct $temp_day
    echo "off" > ~/sct_status
else
    sct $temp_night
    echo "on" > ~/sct_status
fi
