#!/usr/bin/env bash

device_name="Speaker"
device_status=$(amixer sget $device_name | grep -om 1 "\[.*\]")

if [ "$device_status" == "[on]" ];
then
    amixer sset Speaker off
else
    amixer sset Speaker on
fi
