#!/usr/bin/env bash

rm -rfv \
   auto/ \
  *.aux \
  *-blx.bib \
  *.bbl \
  *.bcf \
  *.blg \
  *.dvi \
  *.fdb_latexmk \
  *.fls \
  *.glg \
  *.glo \
  *.gls \
  *.ist \
  *.lof \
  *.log \
  *.lot \
  *.nav \
  *.out \
  *.pytxcode \
  *.run.xml \
  *.snm \
  *.synctex.gz \
  *.toc \
  *.xdv \
