#!/usr/bin/python

import sys
import re

assert len(sys.argv) == 2, "todo_finder requires one input"

keywords = ["TODO", "BUG", "NOTE", "NOW", "XXX"]
excludes = ["\\newcommand{\\TODO}"]
filename = sys.argv[1]
lines = open(filename, "r").read().splitlines()
occurences = []

def check_match(l):

    contains_keyword = any([k in l for k in keywords])
    contains_exclude = any([e in l for e in excludes])
    return contains_keyword and not contains_exclude


def print_formatted(l, i):

    print("\033[0;32m\033[1m" + str(i+1) + ": \033[00m\033[0m", end="")

    formatted = [l]

    for k in keywords:
        parsed = [re.split("(" + k + "+)", s) for s in formatted]
        formatted = [t for s in parsed for t in s]

    for f in formatted:
        if any([k in f for k in keywords]):
            print("\033[0;31m\033[1m" + f + "\033[00m\033[0m", end="")
        else:
            print(f, end="")
    print("\n", end="")


if any([check_match(l) for l in lines]):
    print("\033[0;33m\033[1m" + sys.argv[1] + "\033[00m\033[0m")

for i in range(len(lines)):
    l = lines[i]
    if check_match(l):
        print_formatted(l, i)
