{ pkgs, ... }:
    with pkgs; [
        (callPackage ../programs/bib-down/bib-down.nix { })
        (callPackage ../programs/blur-wallpaper.nix { })
        (callPackage ../programs/bw-get.nix { })
        (callPackage ../programs/cd-fuzzy.nix { })
        (callPackage ../programs/compress-pdf/compress-pdf.nix { })
        (callPackage ../programs/compress-mp3.nix { })
        (callPackage ../programs/feh-fuzzy.nix { })
        (callPackage ../programs/gammatoggle.nix { })
        (callPackage ../programs/latexindent-fast.nix { })
        (callPackage ../programs/long-lines/long-lines.nix { })
        (callPackage ../programs/nixos-update.nix { })
        (callPackage ../programs/pdf-insert-blank-pages.nix { })
        (callPackage ../programs/rclone-sync/rclone-sync.nix { })
        (callPackage ../programs/repos.nix { })
        (callPackage ../programs/rofi-start/rofi-start.nix { })
        (callPackage ../programs/spell-check/spell-check.nix { })
        (callPackage ../programs/spell-check-word.nix { })
        (callPackage ../programs/sway-empty/sway-empty.nix { })
        (callPackage ../programs/tex-check/tex-check.nix { })
        (callPackage ../programs/tex-clean.nix { })
        (callPackage ../programs/todo-finder/todo-finder.nix { })
        (callPackage ../programs/zathura-fuzzy.nix { })
    ]

