#!/usr/bin/env python3

import sys

with open(sys.argv[1], "r") as f:

    lines = f.read().split("\n")
    order = sorted(range(len(lines)), key = lambda i: len(lines[i]))
    sorted_lines = [lines[i] for i in order]

    if len(sorted_lines[-1]) > 80:
        print("\033[0;33m\033[1m" + str(sys.argv[1]) + "\033[00m\033[0m")

    for i in range(len(lines)):
        if len(sorted_lines[i]) > 80:
            print("\033[0;31m\033[1m" + str(len(sorted_lines[i])) + "\033[00m\033[0m",
                  "\033[0;32m\033[1m" + str(order[i]+1).ljust(5) + "\033[00m\033[0m",
                  sorted_lines[i])
